# Generated by Django 3.2.8 on 2021-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=10)),
                ('menu_price', models.CharField(max_length=10)),
                ('menu_quantityr', models.CharField(max_length=12)),
            ],
        ),
    ]
